### ISSUE TITLE
WebSocket stops sending / receiving data when loading a filterscript

### ISSUE THREAD

**Issue by pkfln** [agrippa1994/SA-MP-WebSockets#1] opened 2017-05-11 17:57 UTC
Seems like the WebSocket stops sending and receiving data when I load a filterscript. After unloading the filterscript, the WebSocket still can't receive or send data to the client, but you can still connect to the WebSocket Server.

**Comment by agrippa1994** [comment] 2017-05-13 08:34
Do you use the plugin in the filterscript? I also experienced a similar behavior where I tried to use this plugin in a filterscript. The problem is that each filterscript has its own virtual machine in the samp process but the plugin always uses the main virtual machine of your gamemode. However, the plugin can not be used in a plugin and is a known issue (at least for me).

**Comment by pkfln** [comment] 2017-05-16 06:52
I don't use it in any filterscript, the WebSocket-Server is created in a file, which is included on the gamemode. I could send you an example-project, if you want.

Is there any possible way to fix it?

**Comment by agrippa1994** [comment] 2017-05-18 20:50
Okay, that is strange because include file should not impact the actual gamemode.

There is a way to fix it, but I don't have the time and infrastructure to implement this. The problem is that the callbacks that can be passed via the init functions, e.g., CreateWSClient, are called on main gamemode context. That means, that the callbacks are triggered, but not in your include or filterscript. 

Do functions like WSClientSend / WSServerSend work? How do you use the plugin? Did you create a server or client application?

**Comment by pkfln** [comment] 2017-05-22 06:46
> That means, that the callbacks are triggered, but not in your include or filterscript.

The callbacks in my include get triggered, as long as no filterscript is loaded.


> Do functions like WSClientSend / WSServerSend work?

Haven't tested it yet, because I only send data to the client as soon as the server receives data. Will do it later on today.


> How do you use the plugin? Did you create a server or client application?

I use your plugin as a server application. As a client I use a C# application which uses [websocket-sharp](https://github.com/sta/websocket-sharp).

**Comment by pkfln** [comment] 2017-05-22 20:36
Update: WSServerSend also works when filterscripts are loaded, but it sends "fffixi" to the client, instead of my message, which is weird.

**Comment by alextwothousand** [comment] 2020-06-27 14:53
Any update on this? I'd like to use this plugin.

**Comment by agrippa1994** [comment] 2020-06-27 18:42
Hey, since I will not work on any SA:MP related stuff anymore, I will not fix it. If somebody has a fix, a PR is welcome.

**Comment by alextwothousand** [comment] 2020-07-14 16:46
> Hey, since I will not work on any SA:MP related stuff anymore, I will not fix it. If somebody has a fix, a PR is welcome.

I've made some changes to samp websockets. The changes can be found here: https://github.com/devlexanderxyz/pawn-websockets/

I hope to mitigate some of the issues with the plugin, such as it not working on filterscript loads.

**Comment by agrippa1994** [comment] 2020-07-14 20:08
@devlexanderxyz great work! I hope, that this fixes the issue. If you want, you can create a pull request to merge these changes into this repository (if you do not mind).

**Comment by alextwothousand** [comment] 2020-07-15 15:52
I haven't implemented any fixes with the filterscripts yet, however, I do plan on doing this soon. Once that's done, I'll merge them into a PR :)

**Comment by IS4Code** [comment] 2022-12-23 17:55
Coming a bit late to the party, but yeah, this is totally broken and unusable, and not fixed in @alextwothousand's fork yet. The design of the `PAWN::SetAMX` and `PAWN::GetAMX` functions is wrong and should not be used this way. You should pass the `amx` instance that you receive from the native function everywhere, and store it alongside the callback names too.

**Closed as completed** 2022-12-28 15:02 UTC
